services:
  mikeyaWarehouse_db:
    image: postgres:latest
    container_name: mikeyaWarehouse_db
    env_file:
        - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - mikeyaWarehouse_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mikeyaWarehouse_data: