services:
  mikeyaWarehouse_db:
    image: postgres:latest
    container_name: mikeyaWarehouse_db
    env_file:
        - .env
    environment:
      POSTGRES_USER: ${Database__DB_USER}
      POSTGRES_PASSWORD: ${Database__DB_PASSWORD}
      POSTGRES_DB: ${Database__DB_NAME}
    ports:
      - "${Database__DB_PORT}:5432"
    volumes:
      - mikeyaWarehouse_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mikeyaWarehouse_data: